import {
    RiInstagramLine,
    RiGoogleLine,
    RiFacebookBoxLine,
    RiDiscordLine,
    RiLinkedinLine,
    RiGithubLine,
    RiGitlabLine,
    RiTwitterXFill,
    RiMicrosoftFill,
    RiAppleFill,
    RiAmazonLine,
    RiFirefoxLine,
    RiChromeLine,
    RiStackOverflowLine,
    RiNpmjsLine,
    RiTrelloLine,
    RiSlackLine,
    RiNotionLine,
    RiCodepenLine,
    RiDropboxLine,
    RiDribbbleLine,
    RiBehanceLine,
    RiMediumLine,
    RiGooglePlayLine,
    RiAppStoreLine,
    RiUbuntuLine,
    RiPinterestLine,
    RiSnapchatLine,
    RiWhatsappLine,
    RiTelegramLine,
    RiSkypeLine,
    RiNetflixLine,
    RiSpotifyLine,
    RiBox3Line,
    RiClaudeLine,
    RiFirebaseLine,
    RiOperaFill,
    RiPatreonFill,
    RiPerplexityFill,
    RiProductHuntFill,
    RiSupabaseFill,
    RiThreadsLine,
    RiTiktokLine,
    RiSteamFill,
    RiTwitchFill,
    RiUnsplashFill,
    RiVercelFill,
    RiCloudWindyLine,
  } from "@remixicon/react";
  
  export const items = [
    {
      value: "https://spotify.com",
      label: "Spotify",
      icon: RiSpotifyLine,
    },
    {
      value: "https://netflix.com",
      label: "Netflix",
      icon: RiNetflixLine,
    },
    {
      value: "https://skype.com",
      label: "Skype",
      icon: RiSkypeLine,
    },
    {
      value: "https://telegram.org",
      label: "Telegram",
      icon: RiTelegramLine,
    },
    {
      value: "https://whatsapp.com",
      label: "WhatsApp",
      icon: RiWhatsappLine,
    },
    {
      value: "https://snapchat.com",
      label: "Snapchat",
      icon: RiSnapchatLine,
    },
    {
      value: "https://pinterest.com",
      label: "Pinterest",
      icon: RiPinterestLine,
    },
    {
      value: "https://medium.com",
      label: "Medium",
      icon: RiMediumLine,
    },
    {
      value: "https://behance.net",
      label: "Behance",
      icon: RiBehanceLine,
    },
    {
      value: "https://dribbble.com",
      label: "Dribbble",
      icon: RiDribbbleLine,
    },
    {
      value: "https://ubuntu.com",
      label: "Ubuntu",
      icon: RiUbuntuLine,
    },
    {
      value: "https://apps.apple.com",
      label: "App Store",
      icon: RiAppStoreLine,
    },
    {
      value: "https://play.google.com",
      label: "Google Play",
      icon: RiGooglePlayLine,
    },
    {
      value: "https://instagram.com",
      label: "Instagram",
      icon: RiInstagramLine,
    },
    {
      value: "https://google.com",
      label: "Google",
      icon: RiGoogleLine,
    },
    {
      value: "https://facebook.com",
      label: "Facebook",
      icon: RiFacebookBoxLine,
    },
    {
      value: "https://discord.com",
      label: "Discord",
      icon: RiDiscordLine,
    },
    {
      value: "https://twitter.com",
      label: "Twitter",
      icon: RiTwitterXFill,
    },
    {
      value: "https://linkedin.com",
      label: "LinkedIn",
      icon: RiLinkedinLine,
    },
    {
      value: "https://github.com",
      label: "GitHub",
      icon: RiGithubLine,
    },
    {
      value: "https://gitlab.com",
      label: "GitLab",
      icon: RiGitlabLine,
    },
    {
      value: "https://microsoft.com",
      label: "Microsoft",
      icon: RiMicrosoftFill,
    },
    {
      value: "https://apple.com",
      label: "Apple",
      icon: RiAppleFill,
    },
    {
      value: "https://aws.amazon.com",
      label: "Amazon AWS",
      icon: RiAmazonLine,
    },
    {
      value: "https://stackoverflow.com",
      label: "Stack Overflow",
      icon: RiStackOverflowLine,
    },
    {
      value: "https://npmjs.com",
      label: "NPM",
      icon: RiNpmjsLine,
    },
    {
      value: "https://trello.com",
      label: "Trello",
      icon: RiTrelloLine,
    },
    {
      value: "https://slack.com",
      label: "Slack",
      icon: RiSlackLine,
    },
    {
      value: "https://notion.so",
      label: "Notion",
      icon: RiNotionLine,
    },
    {
      value: "https://codepen.io",
      label: "CodePen",
      icon: RiCodepenLine,
    },
    {
      value: "https://dropbox.com",
      label: "Dropbox",
      icon: RiDropboxLine,
    },
    {
      value: "https://mozilla.org",
      label: "Firefox",
      icon: RiFirefoxLine,
    },
    {
      value: "https://chrome.google.com",
      label: "Chrome",
      icon: RiChromeLine,
    },
    {
      Value: "https://hackthebox.com",
      label: "Hack The Box",
      icon: RiBox3Line,
    },
    {
      value: "https://claude.ai",
      label: "Claude",
      icon: RiClaudeLine,
    },
    {
      value: "https://firebase.google.com",
      label: "Firebase",
      icon: RiFirebaseLine,
    },
    {
      value: "https://opera.com",
      label: "Opera",
      icon: RiOperaFill,
    },
    {
      value: "https://patreon.com",
      label: "Patreon",
      icon: RiPatreonFill,
    },
    {
      value: "https://perplexity.ai",
      label: "Perplexity",
      icon: RiPerplexityFill,
    },
    {
      value: "https://producthunt.com",
      label: "Product Hunt",
      icon: RiProductHuntFill,
    },
    {
      value: "https://supabase.com",
      label: "Supabase",
      icon: RiSupabaseFill,
    },
    {
      value: "https://threads.net",
      label: "Threads",
      icon: RiThreadsLine,
    },
    {
      value: "https://tiktok.com",
      label: "TikTok",
      icon: RiTiktokLine,
    },
    {
      value: "https://steamcommunity.com",
      label: "Steam",
      icon: RiSteamFill,
    },
    {
      value: "https://twitch.tv",
      label: "Twitch",
      icon: RiTwitchFill,
    },
    {
      value: "https://unsplash.com",
      label: "Unsplash",
      icon: RiUnsplashFill,
    },
    {
      value: "https://vercel.com",
      label: "Vercel",
      icon: RiVercelFill
    },
    {
      value: "https://Tryhackme.com",
      label: "TryHackMe",
      icon: RiCloudWindyLine
    }
  ];
  