import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Provider } from "@/provider";

const geistSansLight = localFont({
  src: "./fonts/AtAero-Light.woff2",
  variable: "--font-geist-sans-light",
  weight: "300",
});

const geistSansRegular = localFont({
  src: "./fonts/AtAero-Regular.woff2",
  variable: "--font-geist-sans-regular",
  weight: "400",
});

const geistSansMedium = localFont({
  src: "./fonts/AtAero-Medium.woff2",
  variable: "--font-geist-sans-medium",
  weight: "500",
});

const geistSansSemibold = localFont({
  src: "./fonts/AtAero-Semibold.woff2",
  variable: "--font-geist-sans-semibold",
  weight: "600",
});

const geistSansBold = localFont({
  src: "./fonts/AtAero-Bold.woff2",
  variable: "--font-geist-sans-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSansLight.variable} ${geistSansRegular.variable} ${geistSansMedium.variable} ${geistSansSemibold.variable} ${geistSansBold.variable} antialiased flex flex-col items-center`}
      >
        <div className="page_ambientContainer__xFtyW utils_inert__sliHw">
          <div className="page_ambientLight___Dvmo utils_inert__sliHw">
            <div className="page_lightA__3_ZLn"></div>
            <div className="page_lightB__k6xoL"></div>
            <div className="page_lightC__9Yvpx"></div>
          </div>
        </div>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
